# Generated by Django 3.0.9 on 2020-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('claim_topic', models.CharField(choices=[('INS', 'Installation'), ('SET', 'Settings'), ('REP', 'Repairs')], max_length=30)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PN', 'Pending'), ('IP', 'In progress'), ('DN', 'Done'), ('DC', 'Declined')], default='DR', max_length=2)),
                ('priority', models.CharField(choices=[('LW', 'LOW'), ('MD', 'MEDIUM'), ('HG', 'HIGH')], default='LW', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
