# Generated by Django 3.0.9 on 2020-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0002_auto_20200805_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimmodel',
            name='priority',
            field=models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HG', 'High')], default='LW', max_length=2),
        ),
    ]
