# Generated by Django 3.0.9 on 2020-08-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0006_auto_20200807_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('create_at',)},
        ),
    ]
