# Generated by Django 3.0.9 on 2020-08-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0007_auto_20200808_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='declined_status_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
