# Generated by Django 3.0.9 on 2020-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0008_commentmodel_declined_status_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmodel',
            name='declined_status_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
